import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import NavBar from '@/app/NavBar'
import { GameDataProvider } from '@/context/GameData'
import { processGameLog } from '@/utils/logParser/logParser'
import './globals.css'
import { PropsWithChildren } from 'react'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: PropsWithChildren) {
  const response = await fetch(
    'https://blast-recruiting.s3.eu-central-1.amazonaws.com/NAVIvsVitaGF-Nuke.txt'
  )
  const text = await response.text()
  const gameData = processGameLog(text)

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex h-screen w-screen flex-col gap-4 overflow-hidden bg-slate-900 p-2 text-white">
          <NavBar />
          <GameDataProvider gameData={gameData}>
            <div className="flex flex-1 overflow-hidden">{children}</div>
          </GameDataProvider>
        </div>
      </body>
    </html>
  )
}
